Repository gin-contrib/cors, pull requests merged in 2024-03, with the labels that each got.

#144 test: improve CORS wildcard handling and testing
  cors_test.go
Labels: testing

#106 fixe(domain): wildcard parse bug
  cors.go
Labels: bug

#139 feat(schema): allow usage of custom schemas
  cors.go
  cors_test.go
Labels: enhancement

#145 test(cors): enhance CORS wildcard handling tests
  cors_test.go
Labels: testing

#140 Allow a cors custom validation function which receives the full gin context
  config.go
  cors.go
  cors_test.go
Labels: enhancement
